-- 005 down
ALTER TABLE modules DROP COLUMN IF EXISTS category;
ALTER TABLE modules DROP COLUMN IF EXISTS label;
ALTER TABLE modules DROP COLUMN IF EXISTS tags;
ALTER TABLE modules DROP COLUMN IF EXISTS cover_image;
ALTER TABLE modules DROP COLUMN IF EXISTS accent;
ALTER TABLE modules DROP COLUMN IF EXISTS est_minutes;
