// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdminCourseSource.
const (
	AdminCourseSourceAdmin AdminCourseSource = "admin"
	AdminCourseSourceSeed  AdminCourseSource = "seed"
)

// Valid indicates whether the value is a known member of the AdminCourseSource enum.
func (e AdminCourseSource) Valid() bool {
	switch e {
	case AdminCourseSourceAdmin:
		return true
	case AdminCourseSourceSeed:
		return true
	default:
		return false
	}
}

// Defines values for AdminCourseRowSource.
const (
	AdminCourseRowSourceAdmin AdminCourseRowSource = "admin"
	AdminCourseRowSourceSeed  AdminCourseRowSource = "seed"
)

// Valid indicates whether the value is a known member of the AdminCourseRowSource enum.
func (e AdminCourseRowSource) Valid() bool {
	switch e {
	case AdminCourseRowSourceAdmin:
		return true
	case AdminCourseRowSourceSeed:
		return true
	default:
		return false
	}
}

// Defines values for AdminLessonSource.
const (
	AdminLessonSourceAdmin AdminLessonSource = "admin"
	AdminLessonSourceSeed  AdminLessonSource = "seed"
)

// Valid indicates whether the value is a known member of the AdminLessonSource enum.
func (e AdminLessonSource) Valid() bool {
	switch e {
	case AdminLessonSourceAdmin:
		return true
	case AdminLessonSourceSeed:
		return true
	default:
		return false
	}
}

// Defines values for ContentFormat.
const (
	HTML ContentFormat = "html"
	Md   ContentFormat = "md"
)

// Valid indicates whether the value is a known member of the ContentFormat enum.
func (e ContentFormat) Valid() bool {
	switch e {
	case HTML:
		return true
	case Md:
		return true
	default:
		return false
	}
}

// Defines values for CourseAccessLevel.
const (
	CourseAccessLevelAdmin    CourseAccessLevel = "admin"
	CourseAccessLevelCoauthor CourseAccessLevel = "coauthor"
	CourseAccessLevelOwner    CourseAccessLevel = "owner"
)

// Valid indicates whether the value is a known member of the CourseAccessLevel enum.
func (e CourseAccessLevel) Valid() bool {
	switch e {
	case CourseAccessLevelAdmin:
		return true
	case CourseAccessLevelCoauthor:
		return true
	case CourseAccessLevelOwner:
		return true
	default:
		return false
	}
}

// Defines values for CourseLabel.
const (
	Challenge CourseLabel = "challenge"
	Practice  CourseLabel = "practice"
	Start     CourseLabel = "start"
)

// Valid indicates whether the value is a known member of the CourseLabel enum.
func (e CourseLabel) Valid() bool {
	switch e {
	case Challenge:
		return true
	case Practice:
		return true
	case Start:
		return true
	default:
		return false
	}
}

// Defines values for Difficulty.
const (
	Advanced     Difficulty = "advanced"
	Beginner     Difficulty = "beginner"
	Expert       Difficulty = "expert"
	Intermediate Difficulty = "intermediate"
)

// Valid indicates whether the value is a known member of the Difficulty enum.
func (e Difficulty) Valid() bool {
	switch e {
	case Advanced:
		return true
	case Beginner:
		return true
	case Expert:
		return true
	case Intermediate:
		return true
	default:
		return false
	}
}

// Defines values for GitRefType.
const (
	Branch GitRefType = "branch"
	Head   GitRefType = "head"
	Remote GitRefType = "remote"
	Tag    GitRefType = "tag"
)

// Valid indicates whether the value is a known member of the GitRefType enum.
func (e GitRefType) Valid() bool {
	switch e {
	case Branch:
		return true
	case Head:
		return true
	case Remote:
		return true
	case Tag:
		return true
	default:
		return false
	}
}

// Defines values for ImportIssueLevel.
const (
	ImportIssueLevelError ImportIssueLevel = "error"
	ImportIssueLevelWarn  ImportIssueLevel = "warn"
)

// Valid indicates whether the value is a known member of the ImportIssueLevel enum.
func (e ImportIssueLevel) Valid() bool {
	switch e {
	case ImportIssueLevelError:
		return true
	case ImportIssueLevelWarn:
		return true
	default:
		return false
	}
}

// Defines values for LabMode.
const (
	LabModeCode  LabMode = "code"
	LabModeShell LabMode = "shell"
)

// Valid indicates whether the value is a known member of the LabMode enum.
func (e LabMode) Valid() bool {
	switch e {
	case LabModeCode:
		return true
	case LabModeShell:
		return true
	default:
		return false
	}
}

// Defines values for LabTaskCheckMode.
const (
	Auto   LabTaskCheckMode = "auto"
	Manual LabTaskCheckMode = "manual"
	Tests  LabTaskCheckMode = "tests"
)

// Valid indicates whether the value is a known member of the LabTaskCheckMode enum.
func (e LabTaskCheckMode) Valid() bool {
	switch e {
	case Auto:
		return true
	case Manual:
		return true
	case Tests:
		return true
	default:
		return false
	}
}

// Defines values for LessonKind.
const (
	LessonKindLab    LessonKind = "lab"
	LessonKindQuiz   LessonKind = "quiz"
	LessonKindSQL    LessonKind = "sql"
	LessonKindSim    LessonKind = "sim"
	LessonKindTheory LessonKind = "theory"
)

// Valid indicates whether the value is a known member of the LessonKind enum.
func (e LessonKind) Valid() bool {
	switch e {
	case LessonKindLab:
		return true
	case LessonKindQuiz:
		return true
	case LessonKindSQL:
		return true
	case LessonKindSim:
		return true
	case LessonKindTheory:
		return true
	default:
		return false
	}
}

// Defines values for ProgressStatus.
const (
	Completed  ProgressStatus = "completed"
	InProgress ProgressStatus = "in_progress"
	NotStarted ProgressStatus = "not_started"
)

// Valid indicates whether the value is a known member of the ProgressStatus enum.
func (e ProgressStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case InProgress:
		return true
	case NotStarted:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin   Role = "admin"
	RoleAuthor  Role = "author"
	RoleStudent Role = "student"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleAuthor:
		return true
	case RoleStudent:
		return true
	default:
		return false
	}
}

// Defines values for TaskDifficulty.
const (
	Easy   TaskDifficulty = "easy"
	Hard   TaskDifficulty = "hard"
	Medium TaskDifficulty = "medium"
)

// Valid indicates whether the value is a known member of the TaskDifficulty enum.
func (e TaskDifficulty) Valid() bool {
	switch e {
	case Easy:
		return true
	case Hard:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for TaskKind.
const (
	TaskKindGo    TaskKind = "go"
	TaskKindShell TaskKind = "shell"
)

// Valid indicates whether the value is a known member of the TaskKind enum.
func (e TaskKind) Valid() bool {
	switch e {
	case TaskKindGo:
		return true
	case TaskKindShell:
		return true
	default:
		return false
	}
}

// Defines values for MoveDirection.
const (
	MoveDirectionDown MoveDirection = "down"
	MoveDirectionUp   MoveDirection = "up"
)

// Valid indicates whether the value is a known member of the MoveDirection enum.
func (e MoveDirection) Valid() bool {
	switch e {
	case MoveDirectionDown:
		return true
	case MoveDirectionUp:
		return true
	default:
		return false
	}
}

// Defines values for AdminMoveCourseJSONBodyDirection.
const (
	AdminMoveCourseJSONBodyDirectionDown AdminMoveCourseJSONBodyDirection = "down"
	AdminMoveCourseJSONBodyDirectionUp   AdminMoveCourseJSONBodyDirection = "up"
)

// Valid indicates whether the value is a known member of the AdminMoveCourseJSONBodyDirection enum.
func (e AdminMoveCourseJSONBodyDirection) Valid() bool {
	switch e {
	case AdminMoveCourseJSONBodyDirectionDown:
		return true
	case AdminMoveCourseJSONBodyDirectionUp:
		return true
	default:
		return false
	}
}

// Defines values for AdminMoveLessonJSONBodyDirection.
const (
	AdminMoveLessonJSONBodyDirectionDown AdminMoveLessonJSONBodyDirection = "down"
	AdminMoveLessonJSONBodyDirectionUp   AdminMoveLessonJSONBodyDirection = "up"
)

// Valid indicates whether the value is a known member of the AdminMoveLessonJSONBodyDirection enum.
func (e AdminMoveLessonJSONBodyDirection) Valid() bool {
	switch e {
	case AdminMoveLessonJSONBodyDirectionDown:
		return true
	case AdminMoveLessonJSONBodyDirectionUp:
		return true
	default:
		return false
	}
}

// Defines values for AdminMoveSimulatorJSONBodyDirection.
const (
	AdminMoveSimulatorJSONBodyDirectionDown AdminMoveSimulatorJSONBodyDirection = "down"
	AdminMoveSimulatorJSONBodyDirectionUp   AdminMoveSimulatorJSONBodyDirection = "up"
)

// Valid indicates whether the value is a known member of the AdminMoveSimulatorJSONBodyDirection enum.
func (e AdminMoveSimulatorJSONBodyDirection) Valid() bool {
	switch e {
	case AdminMoveSimulatorJSONBodyDirectionDown:
		return true
	case AdminMoveSimulatorJSONBodyDirectionUp:
		return true
	default:
		return false
	}
}

// Defines values for AdminMoveSpecializationJSONBodyDirection.
const (
	AdminMoveSpecializationJSONBodyDirectionDown AdminMoveSpecializationJSONBodyDirection = "down"
	AdminMoveSpecializationJSONBodyDirectionUp   AdminMoveSpecializationJSONBodyDirection = "up"
)

// Valid indicates whether the value is a known member of the AdminMoveSpecializationJSONBodyDirection enum.
func (e AdminMoveSpecializationJSONBodyDirection) Valid() bool {
	switch e {
	case AdminMoveSpecializationJSONBodyDirectionDown:
		return true
	case AdminMoveSpecializationJSONBodyDirectionUp:
		return true
	default:
		return false
	}
}

// AdminCourse defines model for AdminCourse.
type AdminCourse struct {
	Accent string `json:"accent"`

	// Access What the current user may do with the course.
	Access CourseAccess `json:"access"`

	// Category Stored value; empty when derived.
	Category        string `json:"category"`
	CoverPreviewURL string `json:"cover_preview_url"`

	// CoverURL External cover URL.
	CoverURL    *string    `json:"cover_url"`
	CreatedAt   time.Time  `json:"created_at"`
	Description string     `json:"description"`
	Difficulty  Difficulty `json:"difficulty"`
	EstMinutes  int        `json:"est_minutes"`

	// HasCustomCover Uploaded or external cover is set.
	HasCustomCover bool `json:"has_custom_cover"`
	ID             int  `json:"id"`

	// Label Null when derived.
	Label     *CourseLabel      `json:"label"`
	OrderNum  int               `json:"order_num"`
	Owner     *AuthorRef        `json:"owner"`
	Published bool              `json:"published"`
	Slug      string            `json:"slug"`
	Source    AdminCourseSource `json:"source"`
	Tags      []string          `json:"tags"`
	Title     string            `json:"title"`
	Track     string            `json:"track"`
}

// AdminCourseSource defines model for AdminCourse.Source.
type AdminCourseSource string

// AdminCourseDetail defines model for AdminCourseDetail.
type AdminCourseDetail struct {
	Course  AdminCourse      `json:"course"`
	Lessons []AdminLessonRow `json:"lessons"`
}

// AdminCourseInput defines model for AdminCourseInput.
type AdminCourseInput struct {
	// Accent Cover gradient key; empty → by category.
	Accent *string `json:"accent,omitempty"`

	// Category Empty → derived.
	Category *string `json:"category,omitempty"`

	// CoverURL External http(s) cover. Omitted → cover unchanged; remove it via `DELETE …/cover`.
	CoverURL    *string    `json:"cover_url,omitempty"`
	Description *string    `json:"description,omitempty"`
	Difficulty  Difficulty `json:"difficulty"`

	// EstMinutes 0 → lessons × 10.
	EstMinutes *int `json:"est_minutes,omitempty"`

	// Label Localized on the frontend (Старт / Практика / Вызов).
	Label *CourseLabel `json:"label,omitempty"`

	// Published Omitted → unchanged (draft on create). Changing it needs `can_publish`.
	Published *bool     `json:"published,omitempty"`
	Slug      Slug      `json:"slug"`
	Tags      *[]string `json:"tags,omitempty"`
	Title     string    `json:"title"`

	// Track Existing specialization slug; `gym` is admin only.
	Track string `json:"track"`
}

// AdminCourseRow defines model for AdminCourseRow.
type AdminCourseRow struct {
	Accent string `json:"accent"`

	// Access What the current user may do with the course.
	Access CourseAccess `json:"access"`

	// Category Stored value; empty when derived.
	Category        string `json:"category"`
	CoverPreviewURL string `json:"cover_preview_url"`

	// CoverURL External cover URL.
	CoverURL    *string    `json:"cover_url"`
	CreatedAt   time.Time  `json:"created_at"`
	Description string     `json:"description"`
	Difficulty  Difficulty `json:"difficulty"`
	EstMinutes  int        `json:"est_minutes"`

	// HasCustomCover Uploaded or external cover is set.
	HasCustomCover bool `json:"has_custom_cover"`
	ID             int  `json:"id"`

	// Label Null when derived.
	Label        *CourseLabel         `json:"label"`
	LabsCount    int                  `json:"labs_count"`
	LessonsCount int                  `json:"lessons_count"`
	OrderNum     int                  `json:"order_num"`
	Owner        *AuthorRef           `json:"owner"`
	Published    bool                 `json:"published"`
	Slug         string               `json:"slug"`
	Source       AdminCourseRowSource `json:"source"`
	Tags         []string             `json:"tags"`
	Title        string               `json:"title"`
	Track        string               `json:"track"`
}

// AdminCourseRowSource defines model for AdminCourseRow.Source.
type AdminCourseRowSource string

// AdminLesson defines model for AdminLesson.
type AdminLesson struct {
	Content    string            `json:"content"`
	CourseID   int               `json:"course_id"`
	CreatedAt  time.Time         `json:"created_at"`
	Difficulty Difficulty        `json:"difficulty"`
	Format     ContentFormat     `json:"format"`
	ID         int               `json:"id"`
	Kind       LessonKind        `json:"kind"`
	OrderNum   int               `json:"order_num"`
	Published  bool              `json:"published"`
	Slug       string            `json:"slug"`
	Source     AdminLessonSource `json:"source"`
	Title      string            `json:"title"`
	VMImage    string            `json:"vm_image"`
	VMInit     string            `json:"vm_init"`
}

// AdminLessonSource defines model for AdminLesson.Source.
type AdminLessonSource string

// AdminLessonDetail defines model for AdminLessonDetail.
type AdminLessonDetail struct {
	Lesson    AdminLesson     `json:"lesson"`
	Questions []AdminQuestion `json:"questions"`
	Tasks     []AdminTask     `json:"tasks"`
}

// AdminLessonInput defines model for AdminLessonInput.
type AdminLessonInput struct {
	Content    *string       `json:"content,omitempty"`
	Difficulty Difficulty    `json:"difficulty"`
	Format     ContentFormat `json:"format"`
	Kind       LessonKind    `json:"kind"`

	// Published Omitted → unchanged (draft on create). Changing it needs `can_publish`.
	Published *bool   `json:"published,omitempty"`
	Slug      Slug    `json:"slug"`
	Title     string  `json:"title"`
	VMImage   *string `json:"vm_image,omitempty"`
	VMInit    *string `json:"vm_init,omitempty"`
}

// AdminLessonRow defines model for AdminLessonRow.
type AdminLessonRow struct {
	ID             int        `json:"id"`
	Kind           LessonKind `json:"kind"`
	Published      bool       `json:"published"`
	QuestionsCount int        `json:"questions_count"`
	Slug           string     `json:"slug"`
	TasksCount     int        `json:"tasks_count"`
	Title          string     `json:"title"`
	VMImage        string     `json:"vm_image"`
}

// AdminQuestion defines model for AdminQuestion.
type AdminQuestion struct {
	CorrectIndex       int      `json:"correct_index"`
	Explanation        string   `json:"explanation"`
	ID                 int      `json:"id"`
	LessonID           int      `json:"lesson_id"`
	OptionExplanations []string `json:"option_explanations"`
	Options            []string `json:"options"`
	OrderNum           int      `json:"order_num"`
	Question           string   `json:"question"`
}

// AdminQuestionInput defines model for AdminQuestionInput.
type AdminQuestionInput struct {
	// CorrectIndex 0-based; must be < options length.
	CorrectIndex int     `json:"correct_index"`
	Explanation  *string `json:"explanation,omitempty"`

	// OptionExplanations Empty or the same length as `options`.
	OptionExplanations *[]string `json:"option_explanations,omitempty"`
	Options            []string  `json:"options"`

	// Question HTML allowed; sanitized on render.
	Question string `json:"question"`
}

// AdminSimulator defines model for AdminSimulator.
type AdminSimulator struct {
	Icon      string   `json:"icon"`
	OrderNum  int      `json:"order_num"`
	OwnerID   *int     `json:"owner_id"`
	Published bool     `json:"published"`
	Role      string   `json:"role"`
	Scenario  Scenario `json:"scenario"`
	Slug      string   `json:"slug"`
	Title     string   `json:"title"`
}

// AdminSimulatorInput defines model for AdminSimulatorInput.
type AdminSimulatorInput struct {
	// Published Omitted → unchanged (draft on create).
	Published *bool    `json:"published,omitempty"`
	Scenario  Scenario `json:"scenario"`
}

// AdminSimulatorRow defines model for AdminSimulatorRow.
type AdminSimulatorRow struct {
	Icon      string `json:"icon"`
	OrderNum  int    `json:"order_num"`
	OwnerID   *int   `json:"owner_id"`
	Published bool   `json:"published"`
	Role      string `json:"role"`
	Slug      string `json:"slug"`
	Title     string `json:"title"`
}

// AdminSpecialization defines model for AdminSpecialization.
type AdminSpecialization struct {
	// CoursesCount Courses whose track belongs to the specialization.
	CoursesCount    int    `json:"courses_count"`
	CoverPreviewURL string `json:"cover_preview_url"`

	// CoverURL External cover URL.
	CoverURL       *string `json:"cover_url"`
	Description    string  `json:"description"`
	HasCustomCover bool    `json:"has_custom_cover"`
	Icon           string  `json:"icon"`
	Name           string  `json:"name"`
	OrderNum       int     `json:"order_num"`
	OwnerID        *int    `json:"owner_id"`
	Published      bool    `json:"published"`
	Slug           string  `json:"slug"`
}

// AdminSpecializationInput defines model for AdminSpecializationInput.
type AdminSpecializationInput struct {
	// CoverURL External http(s) cover. Omitted → cover unchanged; remove it via `DELETE …/cover`.
	CoverURL    *string `json:"cover_url,omitempty"`
	Description *string `json:"description,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	Name        string  `json:"name"`

	// Published Omitted → unchanged (draft on create).
	Published *bool `json:"published,omitempty"`
}

// AdminTask defines model for AdminTask.
type AdminTask struct {
	CheckScript  string         `json:"check_script"`
	Description  string         `json:"description"`
	Difficulty   TaskDifficulty `json:"difficulty"`
	Format       ContentFormat  `json:"format"`
	Glossary     []GlossaryItem `json:"glossary"`
	Hints        string         `json:"hints"`
	ID           int            `json:"id"`
	Kind         TaskKind       `json:"kind"`
	LessonID     int            `json:"lesson_id"`
	OrderNum     int            `json:"order_num"`
	SandboxImage string         `json:"sandbox_image"`
	SetupScript  string         `json:"setup_script"`
	Solution     string         `json:"solution"`
	StarterCode  string         `json:"starter_code"`
	TestCases    []TestCase     `json:"test_cases"`
	Title        string         `json:"title"`
}

// AdminTaskInput defines model for AdminTaskInput.
type AdminTaskInput struct {
	CheckScript *string         `json:"check_script,omitempty"`
	Description *string         `json:"description,omitempty"`
	Difficulty  TaskDifficulty  `json:"difficulty"`
	Format      ContentFormat   `json:"format"`
	Glossary    *[]GlossaryItem `json:"glossary,omitempty"`
	Hints       *string         `json:"hints,omitempty"`
	Kind        TaskKind        `json:"kind"`

	// SandboxImage Shell tasks: one of the lab images, e.g. `golearn/sandbox:latest`.
	SandboxImage *string     `json:"sandbox_image,omitempty"`
	SetupScript  *string     `json:"setup_script,omitempty"`
	Solution     *string     `json:"solution,omitempty"`
	StarterCode  *string     `json:"starter_code,omitempty"`
	TestCases    *[]TestCase `json:"test_cases,omitempty"`
	Title        string      `json:"title"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	Blocked   bool                `json:"blocked"`
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	ID        int                 `json:"id"`
	IsSelf    bool                `json:"is_self"`
	Name      string              `json:"name"`

	// Role `author` manages courses they own or co-author; `admin` manages everything.
	Role Role `json:"role"`

	// RolePinnedByEnv Email is in ADMIN_EMAILS.
	RolePinnedByEnv bool `json:"role_pinned_by_env"`
}

// AdminUserPage defines model for AdminUserPage.
type AdminUserPage struct {
	Items []AdminUser `json:"items"`

	// NextCursor Pass as `cursor` for the next page; null on the last page.
	NextCursor *string `json:"next_cursor"`
}

// AuthConfig defines model for AuthConfig.
type AuthConfig struct {
	RegistrationOpen bool `json:"registration_open"`
}

// AuthorRef defines model for AuthorRef.
type AuthorRef struct {
	Email openapi_types.Email `json:"email"`
	ID    int                 `json:"id"`
	Name  string              `json:"name"`
}

// Catalog defines model for Catalog.
type Catalog struct {
	Specializations []SpecializationWithCourses `json:"specializations"`
	Trainers        []CourseCard                `json:"trainers"`
}

// Category Explicit or derived catalog category (DevOps, Linux, Docker, Kubernetes, Git, Database, Golang, Security, …).
type Category = string

// ContentFormat defines model for ContentFormat.
type ContentFormat string

// ContinueLesson defines model for ContinueLesson.
type ContinueLesson struct {
	Course   LinkRef    `json:"course"`
	Kind     LessonKind `json:"kind"`
	Lesson   LinkRef    `json:"lesson"`
	LessonID int        `json:"lesson_id"`
}

// CourseAccess What the current user may do with the course.
type CourseAccess struct {
	// CanDelete Owner and admin.
	CanDelete bool `json:"can_delete"`

	// CanEdit Course fields, cover, lessons, questions, tasks, draft lesson deletion.
	CanEdit bool `json:"can_edit"`

	// CanManageAuthors Add and remove co-authors. Owner and admin.
	CanManageAuthors bool `json:"can_manage_authors"`

	// CanPublish Publish/unpublish the course and its lessons, delete published lessons. Owner and admin.
	CanPublish bool `json:"can_publish"`

	// CanReorder Move the course in the catalog; transfer ownership. Admin only.
	CanReorder bool              `json:"can_reorder"`
	Level      CourseAccessLevel `json:"level"`
}

// CourseAccessLevel defines model for CourseAccess.Level.
type CourseAccessLevel string

// CourseAuthors defines model for CourseAuthors.
type CourseAuthors struct {
	Coauthors []AuthorRef `json:"coauthors"`

	// Owner Null for platform (seed) courses, which only admins manage.
	Owner *AuthorRef `json:"owner"`
}

// CourseCard defines model for CourseCard.
type CourseCard struct {
	// Category Explicit or derived catalog category (DevOps, Linux, Docker, Kubernetes, Git, Database, Golang, Security, …).
	Category    Category   `json:"category"`
	CoverURL    string     `json:"cover_url"`
	Description *string    `json:"description,omitempty"`
	Difficulty  Difficulty `json:"difficulty"`
	EstMinutes  int        `json:"est_minutes"`
	ID          int        `json:"id"`

	// Label Localized on the frontend (Старт / Практика / Вызов).
	Label            CourseLabel    `json:"label"`
	LessonsCompleted int            `json:"lessons_completed"`
	LessonsCount     int            `json:"lessons_count"`
	ProgressPct      int            `json:"progress_pct"`
	Slug             string         `json:"slug"`
	SpecSlug         string         `json:"spec_slug"`
	Status           ProgressStatus `json:"status"`
	Tags             []string       `json:"tags"`
	Title            string         `json:"title"`
}

// CourseDetail defines model for CourseDetail.
type CourseDetail struct {
	CompletedCount int          `json:"completed_count"`
	Course         CourseCard   `json:"course"`
	Items          []CourseItem `json:"items"`
	NextCourse     *LinkRef     `json:"next_course,omitempty"`
	PrevCourse     *LinkRef     `json:"prev_course,omitempty"`
	ProgressPct    int          `json:"progress_pct"`
}

// CourseDocument Portable course format (`internal/courseio`). Order comes from array position.
type CourseDocument struct {
	Accent   *string `json:"accent,omitempty"`
	Category *string `json:"category,omitempty"`

	// CoverImage URL or data URI.
	CoverImage  *string                `json:"cover_image,omitempty"`
	Description *string                `json:"description,omitempty"`
	Difficulty  *string                `json:"difficulty,omitempty"`
	EstMinutes  *int                   `json:"est_minutes,omitempty"`
	Label       *string                `json:"label,omitempty"`
	Lessons     []CourseDocumentLesson `json:"lessons"`
	OrderNum    *int                   `json:"order_num,omitempty"`
	Slug        Slug                   `json:"slug"`
	Tags        *[]string              `json:"tags,omitempty"`
	Title       string                 `json:"title"`
	Track       *string                `json:"track,omitempty"`
}

// CourseDocumentLesson defines model for CourseDocumentLesson.
type CourseDocumentLesson struct {
	Content    *string                   `json:"content,omitempty"`
	Difficulty *string                   `json:"difficulty,omitempty"`
	Format     *string                   `json:"format,omitempty"`
	Kind       *string                   `json:"kind,omitempty"`
	Quiz       *[]CourseDocumentQuestion `json:"quiz,omitempty"`
	Slug       string                    `json:"slug"`
	Tasks      *[]CourseDocumentTask     `json:"tasks,omitempty"`
	Title      string                    `json:"title"`
	VMImage    *string                   `json:"vm_image,omitempty"`
	VMInit     *string                   `json:"vm_init,omitempty"`
}

// CourseDocumentQuestion defines model for CourseDocumentQuestion.
type CourseDocumentQuestion struct {
	// Correct 1-based.
	Correct     int       `json:"correct"`
	Explanation *string   `json:"explanation,omitempty"`
	OptionExpl  *[]string `json:"option_expl,omitempty"`
	Options     []string  `json:"options"`
	Question    string    `json:"question"`
}

// CourseDocumentTask defines model for CourseDocumentTask.
type CourseDocumentTask struct {
	CheckScript  *string         `json:"check_script,omitempty"`
	Description  *string         `json:"description,omitempty"`
	Difficulty   *string         `json:"difficulty,omitempty"`
	Format       *string         `json:"format,omitempty"`
	Glossary     *[]GlossaryItem `json:"glossary,omitempty"`
	Hints        *string         `json:"hints,omitempty"`
	Kind         *string         `json:"kind,omitempty"`
	SandboxImage *string         `json:"sandbox_image,omitempty"`
	SetupScript  *string         `json:"setup_script,omitempty"`
	Solution     *string         `json:"solution,omitempty"`
	StarterCode  *string         `json:"starter_code,omitempty"`
	TestCases    *[]TestCase     `json:"test_cases,omitempty"`
	Title        string          `json:"title"`
}

// CourseItem defines model for CourseItem.
type CourseItem struct {
	// IsNext First not completed item.
	IsNext   bool           `json:"is_next"`
	Kind     LessonKind     `json:"kind"`
	LessonID int            `json:"lesson_id"`
	Slug     string         `json:"slug"`
	Status   ProgressStatus `json:"status"`
	Title    string         `json:"title"`
}

// CourseLabel Localized on the frontend (Старт / Практика / Вызов).
type CourseLabel string

// Dashboard defines model for Dashboard.
type Dashboard struct {
	// Activity `YYYY-MM-DD` → activity count, last 365 days.
	Activity map[string]int `json:"activity"`

	// Continue Latest in-progress lesson.
	Continue *ContinueLesson   `json:"continue,omitempty"`
	Overview DashboardOverview `json:"overview"`
}

// DashboardOverview defines model for DashboardOverview.
type DashboardOverview struct {
	ActiveDays   int `json:"active_days"`
	LabsDone     int `json:"labs_done"`
	LabsTotal    int `json:"labs_total"`
	LessonsRead  int `json:"lessons_read"`
	LessonsTotal int `json:"lessons_total"`

	// SimulatorsDone Not tracked yet — always 0.
	SimulatorsDone  int `json:"simulators_done"`
	SimulatorsTotal int `json:"simulators_total"`
	Streak          int `json:"streak"`
	TasksSolved     int `json:"tasks_solved"`
	TestsPassed     int `json:"tests_passed"`

	// TrainersDone Completed trainer (gym) courses.
	TrainersDone  int `json:"trainers_done"`
	TrainersTotal int `json:"trainers_total"`
}

// Difficulty defines model for Difficulty.
type Difficulty string

// Error defines model for Error.
type Error struct {
	Error ErrorBody `json:"error"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	// Code Examples: unauthorized, forbidden, not_found, validation_failed, slug_taken, already_author, sandbox_disabled
	Code    string        `json:"code"`
	Details *ErrorDetails `json:"details,omitempty"`

	// Message Developer-facing, not localized.
	Message string `json:"message"`
}

// ErrorDetails defines model for ErrorDetails.
type ErrorDetails struct {
	// Fields Field name → error code (`required`, `too_short`, `too_long`, `invalid_format`, `invalid_value`, `not_found`, `not_author`).
	Fields *map[string]string `json:"fields,omitempty"`
	Issues *[]ImportIssue     `json:"issues,omitempty"`
}

// GitCommit defines model for GitCommit.
type GitCommit struct {
	Hash    string   `json:"hash"`
	Parents []string `json:"parents"`
	Refs    []GitRef `json:"refs"`
	Subject string   `json:"subject"`
}

// GitGraph defines model for GitGraph.
type GitGraph struct {
	Commits []GitCommit `json:"commits"`
}

// GitRef defines model for GitRef.
type GitRef struct {
	Name string     `json:"name"`
	Type GitRefType `json:"type"`
}

// GitRefType defines model for GitRef.Type.
type GitRefType string

// GlossaryItem defines model for GlossaryItem.
type GlossaryItem struct {
	Definition string `json:"definition"`
	Term       string `json:"term"`
}

// ImportIssue defines model for ImportIssue.
type ImportIssue struct {
	// Code Examples: no_lessons, lesson_slug_empty, lesson_slug_invalid, lesson_slug_duplicate, lesson_title_empty, unknown_kind, unknown_format, too_few_options, correct_out_of_range, task_title_empty, unknown_sandbox_image, check_without_image
	Code       string           `json:"code"`
	LessonSlug *string          `json:"lesson_slug,omitempty"`
	Level      ImportIssueLevel `json:"level"`

	// Message Developer-facing, not localized.
	Message string `json:"message"`

	// Path JSON pointer, e.g. `/lessons/2/quiz/0/correct`.
	Path *string `json:"path,omitempty"`
}

// ImportIssueLevel defines model for ImportIssue.Level.
type ImportIssueLevel string

// ImportPreview defines model for ImportPreview.
type ImportPreview struct {
	Blocked      bool          `json:"blocked"`
	Exists       bool          `json:"exists"`
	Issues       []ImportIssue `json:"issues"`
	LessonsCount int           `json:"lessons_count"`

	// LostProgress Student progress rows on lessons the import deletes.
	LostProgress int `json:"lost_progress"`

	// LostSubmissions Student submissions on tasks the import deletes.
	LostSubmissions int       `json:"lost_submissions"`
	NewLessons      []LinkRef `json:"new_lessons"`
	RemovedLessons  []LinkRef `json:"removed_lessons"`
	Slug            string    `json:"slug"`
	Title           string    `json:"title"`
	UpdatedLessons  []LinkRef `json:"updated_lessons"`
}

// ImportResult defines model for ImportResult.
type ImportResult struct {
	CourseID int  `json:"course_id"`
	Created  bool `json:"created"`
}

// Lab defines model for Lab.
type Lab struct {
	IsGitLab   bool           `json:"is_git_lab"`
	LessonID   int            `json:"lesson_id"`
	Mode       LabMode        `json:"mode"`
	Nav        LessonNav      `json:"nav"`
	Progress   LessonProgress `json:"progress"`
	Quiz       *LessonQuiz    `json:"quiz,omitempty"`
	Sandbox    SandboxSession `json:"sandbox"`
	Slug       string         `json:"slug"`
	Tasks      []LabTask      `json:"tasks"`
	TheoryHTML string         `json:"theory_html"`
	Title      string         `json:"title"`
}

// LabMode defines model for Lab.Mode.
type LabMode string

// LabDirListing defines model for LabDirListing.
type LabDirListing struct {
	Entries []LabFileEntry `json:"entries"`
	Path    string         `json:"path"`
}

// LabFileEntry defines model for LabFileEntry.
type LabFileEntry struct {
	IsDir bool   `json:"is_dir"`
	Name  string `json:"name"`
}

// LabTask defines model for LabTask.
type LabTask struct {
	// CheckMode `auto` → POST /check, `tests` → POST /run, `manual` → POST /done.
	CheckMode       LabTaskCheckMode `json:"check_mode"`
	DescriptionHTML string           `json:"description_html"`
	Glossary        []GlossaryItem   `json:"glossary"`
	HintsHTML       *string          `json:"hints_html,omitempty"`
	ID              int              `json:"id"`
	Kind            TaskKind         `json:"kind"`
	Passed          bool             `json:"passed"`

	// StarterCode Go tasks only.
	StarterCode *string `json:"starter_code,omitempty"`
	Title       string  `json:"title"`
}

// LabTaskCheckMode `auto` → POST /check, `tests` → POST /run, `manual` → POST /done.
type LabTaskCheckMode string

// Landing defines model for Landing.
type Landing struct {
	Stats  LandingStats   `json:"stats"`
	Tracks []LandingTrack `json:"tracks"`
}

// LandingStats defines model for LandingStats.
type LandingStats struct {
	AutoCheckedTasks int `json:"auto_checked_tasks"`
	Courses          int `json:"courses"`
	Labs             int `json:"labs"`
	Lessons          int `json:"lessons"`
}

// LandingTrack defines model for LandingTrack.
type LandingTrack struct {
	CoursesCount int    `json:"courses_count"`
	Description  string `json:"description"`
	Icon         string `json:"icon"`
	Name         string `json:"name"`
	Slug         string `json:"slug"`
}

// LessonDetail defines model for LessonDetail.
type LessonDetail struct {
	ContentHTML string         `json:"content_html"`
	HasLab      bool           `json:"has_lab"`
	ID          int            `json:"id"`
	Kind        LessonKind     `json:"kind"`
	Nav         LessonNav      `json:"nav"`
	Progress    LessonProgress `json:"progress"`
	Quiz        *LessonQuiz    `json:"quiz,omitempty"`
	Slug        string         `json:"slug"`
	SQLSchema   *SQLSchema     `json:"sql_schema,omitempty"`
	Title       string         `json:"title"`
}

// LessonKind defines model for LessonKind.
type LessonKind string

// LessonLink defines model for LessonLink.
type LessonLink struct {
	Kind  LessonKind `json:"kind"`
	Slug  string     `json:"slug"`
	Title string     `json:"title"`
}

// LessonNav defines model for LessonNav.
type LessonNav struct {
	Course            LinkRef     `json:"course"`
	CourseProgressPct int         `json:"course_progress_pct"`
	Next              *LessonLink `json:"next,omitempty"`

	// Position 1-based among published lessons.
	Position int         `json:"position"`
	Prev     *LessonLink `json:"prev,omitempty"`
	Total    int         `json:"total"`
}

// LessonProgress defines model for LessonProgress.
type LessonProgress struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	Notes       string     `json:"notes"`

	// QuizAttempts Number of submitted quiz attempts.
	QuizAttempts int `json:"quiz_attempts"`

	// QuizScore Score of the latest submitted attempt.
	QuizScore *int           `json:"quiz_score,omitempty"`
	QuizTotal *int           `json:"quiz_total,omitempty"`
	Status    ProgressStatus `json:"status"`
}

// LessonQuiz defines model for LessonQuiz.
type LessonQuiz struct {
	Questions []QuizQuestionPublic `json:"questions"`
}

// LinkRef defines model for LinkRef.
type LinkRef struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

// Me defines model for Me.
type Me struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	ID        int                 `json:"id"`
	IsAdmin   bool                `json:"is_admin"`
	Name      string              `json:"name"`

	// Role `author` manages courses they own or co-author; `admin` manages everything.
	Role Role `json:"role"`
}

// Profile defines model for Profile.
type Profile struct {
	LessonsCompleted int `json:"lessons_completed"`
	LessonsStarted   int `json:"lessons_started"`
	User             Me  `json:"user"`
}

// ProgressStatus defines model for ProgressStatus.
type ProgressStatus string

// QuizAnswerInput defines model for QuizAnswerInput.
type QuizAnswerInput struct {
	QuestionID    int `json:"question_id"`
	SelectedIndex int `json:"selected_index"`
}

// QuizAnswerResult defines model for QuizAnswerResult.
type QuizAnswerResult struct {
	CorrectIndex    int     `json:"correct_index"`
	ExplanationHTML *string `json:"explanation_html,omitempty"`
	IsCorrect       bool    `json:"is_correct"`

	// Locked True when this is a previously stored answer.
	Locked                 bool      `json:"locked"`
	OptionExplanationsHTML *[]string `json:"option_explanations_html,omitempty"`
	QuestionID             int       `json:"question_id"`
	SelectedIndex          int       `json:"selected_index"`
}

// QuizQuestionPublic defines model for QuizQuestionPublic.
type QuizQuestionPublic struct {
	// Answer Present if this question was already answered in the current attempt.
	Answer       *QuizAnswerResult `json:"answer,omitempty"`
	ID           int               `json:"id"`
	OptionsHTML  []string          `json:"options_html"`
	QuestionHTML string            `json:"question_html"`
}

// QuizQuestionResult defines model for QuizQuestionResult.
type QuizQuestionResult struct {
	CorrectIndex    int      `json:"correct_index"`
	ExplanationHTML *string  `json:"explanation_html,omitempty"`
	IsCorrect       bool     `json:"is_correct"`
	OptionsHTML     []string `json:"options_html"`
	QuestionHTML    string   `json:"question_html"`
	QuestionID      int      `json:"question_id"`

	// SelectedIndex Null when unanswered.
	SelectedIndex *int `json:"selected_index"`
}

// QuizResult defines model for QuizResult.
type QuizResult struct {
	// Attempt 1-based number of this attempt.
	Attempt int                  `json:"attempt"`
	Percent int                  `json:"percent"`
	Results []QuizQuestionResult `json:"results"`
	Score   int                  `json:"score"`
	Total   int                  `json:"total"`
}

// Role `author` manages courses they own or co-author; `admin` manages everything.
type Role string

// RunRequest defines model for RunRequest.
type RunRequest struct {
	Code  string  `json:"code"`
	Stdin *string `json:"stdin,omitempty"`
}

// RunResult defines model for RunResult.
type RunResult struct {
	AllPassed    *bool            `json:"all_passed,omitempty"`
	Errors       string           `json:"errors"`
	ExitCode     int              `json:"exit_code"`
	LessonStatus *ProgressStatus  `json:"lesson_status,omitempty"`
	Output       string           `json:"output"`
	TestResults  *[]RunTestResult `json:"test_results,omitempty"`
	TimedOut     bool             `json:"timed_out"`
}

// RunTestResult defines model for RunTestResult.
type RunTestResult struct {
	Actual string `json:"actual"`
	Index  int    `json:"index"`
	Input  string `json:"input"`
	Passed bool   `json:"passed"`
}

// SandboxSession defines model for SandboxSession.
type SandboxSession struct {
	// Enabled Sandbox configured on the server.
	Enabled bool `json:"enabled"`

	// ExpiresAt Idle timeout (30 min) or hard limit (1 h), whichever is sooner.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Running   bool       `json:"running"`
	StartedAt *time.Time `json:"started_at,omitempty"`
}

// Scenario defines model for Scenario.
type Scenario struct {
	Icon    string           `json:"icon"`
	Intro   string           `json:"intro"`
	Metrics []ScenarioMetric `json:"metrics"`
	Role    string           `json:"role"`
	Slug    Slug             `json:"slug"`
	Title   string           `json:"title"`
	Turns   []ScenarioTurn   `json:"turns"`
}

// ScenarioChoice defines model for ScenarioChoice.
type ScenarioChoice struct {
	// Effects Metric key → integer delta; keys must exist in `metrics`.
	Effects map[string]int `json:"effects"`
	Result  string         `json:"result"`
	Text    string         `json:"text"`
}

// ScenarioMetric defines model for ScenarioMetric.
type ScenarioMetric struct {
	// Higher Higher value is better.
	Higher bool   `json:"higher"`
	Key    string `json:"key"`
	Label  string `json:"label"`
	Start  int    `json:"start"`
	Unit   string `json:"unit"`
}

// ScenarioTurn defines model for ScenarioTurn.
type ScenarioTurn struct {
	Choices   []ScenarioChoice `json:"choices"`
	Situation string           `json:"situation"`
	Title     string           `json:"title"`
}

// SimulatorSummary defines model for SimulatorSummary.
type SimulatorSummary struct {
	Icon       string `json:"icon"`
	Role       string `json:"role"`
	Slug       string `json:"slug"`
	Title      string `json:"title"`
	TurnsCount int    `json:"turns_count"`
}

// Slug defines model for Slug.
type Slug = string

// Specialization defines model for Specialization.
type Specialization struct {
	// CoverURL Always `/api/v1/specializations/{slug}/cover`.
	CoverURL    string `json:"cover_url"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
}

// SpecializationWithCourses defines model for SpecializationWithCourses.
type SpecializationWithCourses struct {
	Courses     []CourseCard `json:"courses"`
	CoursesDone int          `json:"courses_done"`

	// CoverURL Always `/api/v1/specializations/{slug}/cover`.
	CoverURL    string `json:"cover_url"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
}

// SQLColumn defines model for SqlColumn.
type SQLColumn struct {
	Description *string `json:"description,omitempty"`
	IsKey       bool    `json:"is_key"`
	Name        string  `json:"name"`
	Type        string  `json:"type"`
}

// SQLSchema SQL practice data (was the `.sql-erd[data-schema]` island in content HTML).
type SQLSchema struct {
	// Ddl SQLite CREATE TABLE statements for sql.js.
	Ddl             string     `json:"ddl"`
	ExpectedColumns []string   `json:"expected_columns"`
	Tables          []SQLTable `json:"tables"`
	Title           string     `json:"title"`
}

// SQLTable defines model for SqlTable.
type SQLTable struct {
	Columns []SQLColumn `json:"columns"`
	ID      string      `json:"id"`
}

// TaskCheckResult defines model for TaskCheckResult.
type TaskCheckResult struct {
	LessonStatus ProgressStatus `json:"lesson_status"`

	// Output Check script output (stdout+stderr, truncated).
	Output *string `json:"output,omitempty"`
	Passed bool    `json:"passed"`
	TaskID int     `json:"task_id"`
}

// TaskDifficulty defines model for TaskDifficulty.
type TaskDifficulty string

// TaskKind defines model for TaskKind.
type TaskKind string

// TestCase defines model for TestCase.
type TestCase struct {
	ExpectedOutput string `json:"expected_output"`
	Input          string `json:"input"`
}

// CourseID defines model for CourseId.
type CourseID = int

// CourseSlug defines model for CourseSlug.
type CourseSlug = Slug

// Cursor defines model for Cursor.
type Cursor = string

// LessonID defines model for LessonId.
type LessonID = int

// LessonSlug defines model for LessonSlug.
type LessonSlug = Slug

// Limit defines model for Limit.
type Limit = int

// SandboxPath defines model for SandboxPath.
type SandboxPath = string

// SimSlug defines model for SimSlug.
type SimSlug = Slug

// SpecSlug defines model for SpecSlug.
type SpecSlug = Slug

// TaskID defines model for TaskId.
type TaskID = int

// TermCols defines model for TermCols.
type TermCols = int

// TermRows defines model for TermRows.
type TermRows = int

// UserID defines model for UserId.
type UserID = int

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InvalidCredentials defines model for InvalidCredentials.
type InvalidCredentials = Error

// NotFound defines model for NotFound.
type NotFound = Error

// PathOutsideJail defines model for PathOutsideJail.
type PathOutsideJail = Error

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = Error

// RateLimited defines model for RateLimited.
type RateLimited = Error

// SandboxDisabled defines model for SandboxDisabled.
type SandboxDisabled = Error

// SandboxError defines model for SandboxError.
type SandboxError = Error

// SandboxNotRunning defines model for SandboxNotRunning.
type SandboxNotRunning = Error

// SlugTaken defines model for SlugTaken.
type SlugTaken = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnsupportedMedia defines model for UnsupportedMedia.
type UnsupportedMedia = Error

// ValidationFailed defines model for ValidationFailed.
type ValidationFailed = Error

// Move defines model for Move.
type Move struct {
	Direction MoveDirection `json:"direction"`
}

// MoveDirection defines model for Move.Direction.
type MoveDirection string

// Published defines model for Published.
type Published struct {
	Published bool `json:"published"`
}

// AdminPreviewContentJSONBody defines parameters for AdminPreviewContent.
type AdminPreviewContentJSONBody struct {
	Content string        `json:"content"`
	Format  ContentFormat `json:"format"`
}

// AdminAddCourseAuthorJSONBody defines parameters for AdminAddCourseAuthor.
type AdminAddCourseAuthorJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// AdminUploadCourseCoverMultipartBody defines parameters for AdminUploadCourseCover.
type AdminUploadCourseCoverMultipartBody struct {
	// File PNG, JPEG, WebP or SVG, max 4 MiB.
	File openapi_types.File `json:"file"`
}

// AdminMoveCourseJSONBody defines parameters for AdminMoveCourse.
type AdminMoveCourseJSONBody struct {
	Direction AdminMoveCourseJSONBodyDirection `json:"direction"`
}

// AdminMoveCourseJSONBodyDirection defines parameters for AdminMoveCourse.
type AdminMoveCourseJSONBodyDirection string

// AdminSetCourseOwnerJSONBody defines parameters for AdminSetCourseOwner.
type AdminSetCourseOwnerJSONBody struct {
	UserID int `json:"user_id"`
}

// AdminSetCoursePublishedJSONBody defines parameters for AdminSetCoursePublished.
type AdminSetCoursePublishedJSONBody struct {
	Published bool `json:"published"`
}

// AdminMoveLessonJSONBody defines parameters for AdminMoveLesson.
type AdminMoveLessonJSONBody struct {
	Direction AdminMoveLessonJSONBodyDirection `json:"direction"`
}

// AdminMoveLessonJSONBodyDirection defines parameters for AdminMoveLesson.
type AdminMoveLessonJSONBodyDirection string

// AdminSetLessonPublishedJSONBody defines parameters for AdminSetLessonPublished.
type AdminSetLessonPublishedJSONBody struct {
	Published bool `json:"published"`
}

// AdminMoveSimulatorJSONBody defines parameters for AdminMoveSimulator.
type AdminMoveSimulatorJSONBody struct {
	Direction AdminMoveSimulatorJSONBodyDirection `json:"direction"`
}

// AdminMoveSimulatorJSONBodyDirection defines parameters for AdminMoveSimulator.
type AdminMoveSimulatorJSONBodyDirection string

// AdminSetSimulatorPublishedJSONBody defines parameters for AdminSetSimulatorPublished.
type AdminSetSimulatorPublishedJSONBody struct {
	Published bool `json:"published"`
}

// AdminCreateSpecializationJSONBody defines parameters for AdminCreateSpecialization.
type AdminCreateSpecializationJSONBody struct {
	// CoverURL External http(s) cover. Omitted → cover unchanged; remove it via `DELETE …/cover`.
	CoverURL    *string `json:"cover_url,omitempty"`
	Description *string `json:"description,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	Name        string  `json:"name"`

	// Published Omitted → unchanged (draft on create).
	Published *bool `json:"published,omitempty"`
	Slug      Slug  `json:"slug"`
}

// AdminUploadSpecializationCoverMultipartBody defines parameters for AdminUploadSpecializationCover.
type AdminUploadSpecializationCoverMultipartBody struct {
	// File PNG, JPEG, WebP or SVG, max 4 MiB.
	File openapi_types.File `json:"file"`
}

// AdminMoveSpecializationJSONBody defines parameters for AdminMoveSpecialization.
type AdminMoveSpecializationJSONBody struct {
	Direction AdminMoveSpecializationJSONBodyDirection `json:"direction"`
}

// AdminMoveSpecializationJSONBodyDirection defines parameters for AdminMoveSpecialization.
type AdminMoveSpecializationJSONBodyDirection string

// AdminSetSpecializationPublishedJSONBody defines parameters for AdminSetSpecializationPublished.
type AdminSetSpecializationPublishedJSONBody struct {
	Published bool `json:"published"`
}

// AdminListUsersParams defines parameters for AdminListUsers.
type AdminListUsersParams struct {
	// Q Substring match on name or email.
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// AdminCreateUserJSONBody defines parameters for AdminCreateUser.
type AdminCreateUserJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`

	// Role `author` manages courses they own or co-author; `admin` manages everything.
	Role Role `json:"role"`
}

// AdminUpdateUserJSONBody defines parameters for AdminUpdateUser.
type AdminUpdateUserJSONBody struct {
	Blocked *bool `json:"blocked,omitempty"`

	// Role `author` manages courses they own or co-author; `admin` manages everything.
	Role *Role `json:"role,omitempty"`
}

// AdminSetUserPasswordJSONBody defines parameters for AdminSetUserPassword.
type AdminSetUserPasswordJSONBody struct {
	Password string `json:"password"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

// OpenGitTrainerTerminalParams defines parameters for OpenGitTrainerTerminal.
type OpenGitTrainerTerminalParams struct {
	Cols *TermCols `form:"cols,omitempty" json:"cols,omitempty"`
	Rows *TermRows `form:"rows,omitempty" json:"rows,omitempty"`
}

// ReadLabFileParams defines parameters for ReadLabFile.
type ReadLabFileParams struct {
	// Path Absolute or `/root`-relative path; must stay inside `/root`.
	Path *SandboxPath `form:"path,omitempty" json:"path,omitempty"`
}

// WriteLabFileParams defines parameters for WriteLabFile.
type WriteLabFileParams struct {
	// Path Absolute or `/root`-relative path; must stay inside `/root`.
	Path *SandboxPath `form:"path,omitempty" json:"path,omitempty"`
}

// ListLabFilesParams defines parameters for ListLabFiles.
type ListLabFilesParams struct {
	// Path Absolute or `/root`-relative path; must stay inside `/root`.
	Path *SandboxPath `form:"path,omitempty" json:"path,omitempty"`
}

// OpenLabTerminalParams defines parameters for OpenLabTerminal.
type OpenLabTerminalParams struct {
	Cols *TermCols `form:"cols,omitempty" json:"cols,omitempty"`
	Rows *TermRows `form:"rows,omitempty" json:"rows,omitempty"`
}

// SaveLessonNotesJSONBody defines parameters for SaveLessonNotes.
type SaveLessonNotesJSONBody struct {
	Notes string `json:"notes"`
}

// SubmitQuizJSONBody defines parameters for SubmitQuiz.
type SubmitQuizJSONBody struct {
	Answers *[]QuizAnswerInput `json:"answers,omitempty"`
}

// AdminPreviewContentJSONRequestBody defines body for AdminPreviewContent for application/json ContentType.
type AdminPreviewContentJSONRequestBody AdminPreviewContentJSONBody

// AdminCreateCourseJSONRequestBody defines body for AdminCreateCourse for application/json ContentType.
type AdminCreateCourseJSONRequestBody = AdminCourseInput

// AdminUpdateCourseJSONRequestBody defines body for AdminUpdateCourse for application/json ContentType.
type AdminUpdateCourseJSONRequestBody = AdminCourseInput

// AdminAddCourseAuthorJSONRequestBody defines body for AdminAddCourseAuthor for application/json ContentType.
type AdminAddCourseAuthorJSONRequestBody AdminAddCourseAuthorJSONBody

// AdminUploadCourseCoverMultipartRequestBody defines body for AdminUploadCourseCover for multipart/form-data ContentType.
type AdminUploadCourseCoverMultipartRequestBody AdminUploadCourseCoverMultipartBody

// AdminCreateLessonJSONRequestBody defines body for AdminCreateLesson for application/json ContentType.
type AdminCreateLessonJSONRequestBody = AdminLessonInput

// AdminMoveCourseJSONRequestBody defines body for AdminMoveCourse for application/json ContentType.
type AdminMoveCourseJSONRequestBody AdminMoveCourseJSONBody

// AdminSetCourseOwnerJSONRequestBody defines body for AdminSetCourseOwner for application/json ContentType.
type AdminSetCourseOwnerJSONRequestBody AdminSetCourseOwnerJSONBody

// AdminSetCoursePublishedJSONRequestBody defines body for AdminSetCoursePublished for application/json ContentType.
type AdminSetCoursePublishedJSONRequestBody AdminSetCoursePublishedJSONBody

// AdminApplyImportJSONRequestBody defines body for AdminApplyImport for application/json ContentType.
type AdminApplyImportJSONRequestBody = CourseDocument

// AdminPreviewImportJSONRequestBody defines body for AdminPreviewImport for application/json ContentType.
type AdminPreviewImportJSONRequestBody = CourseDocument

// AdminUpdateLessonJSONRequestBody defines body for AdminUpdateLesson for application/json ContentType.
type AdminUpdateLessonJSONRequestBody = AdminLessonInput

// AdminMoveLessonJSONRequestBody defines body for AdminMoveLesson for application/json ContentType.
type AdminMoveLessonJSONRequestBody AdminMoveLessonJSONBody

// AdminSetLessonPublishedJSONRequestBody defines body for AdminSetLessonPublished for application/json ContentType.
type AdminSetLessonPublishedJSONRequestBody AdminSetLessonPublishedJSONBody

// AdminCreateQuestionJSONRequestBody defines body for AdminCreateQuestion for application/json ContentType.
type AdminCreateQuestionJSONRequestBody = AdminQuestionInput

// AdminCreateTaskJSONRequestBody defines body for AdminCreateTask for application/json ContentType.
type AdminCreateTaskJSONRequestBody = AdminTaskInput

// AdminUpdateQuestionJSONRequestBody defines body for AdminUpdateQuestion for application/json ContentType.
type AdminUpdateQuestionJSONRequestBody = AdminQuestionInput

// AdminCreateSimulatorJSONRequestBody defines body for AdminCreateSimulator for application/json ContentType.
type AdminCreateSimulatorJSONRequestBody = AdminSimulatorInput

// AdminUpdateSimulatorJSONRequestBody defines body for AdminUpdateSimulator for application/json ContentType.
type AdminUpdateSimulatorJSONRequestBody = AdminSimulatorInput

// AdminMoveSimulatorJSONRequestBody defines body for AdminMoveSimulator for application/json ContentType.
type AdminMoveSimulatorJSONRequestBody AdminMoveSimulatorJSONBody

// AdminSetSimulatorPublishedJSONRequestBody defines body for AdminSetSimulatorPublished for application/json ContentType.
type AdminSetSimulatorPublishedJSONRequestBody AdminSetSimulatorPublishedJSONBody

// AdminCreateSpecializationJSONRequestBody defines body for AdminCreateSpecialization for application/json ContentType.
type AdminCreateSpecializationJSONRequestBody AdminCreateSpecializationJSONBody

// AdminUpdateSpecializationJSONRequestBody defines body for AdminUpdateSpecialization for application/json ContentType.
type AdminUpdateSpecializationJSONRequestBody = AdminSpecializationInput

// AdminUploadSpecializationCoverMultipartRequestBody defines body for AdminUploadSpecializationCover for multipart/form-data ContentType.
type AdminUploadSpecializationCoverMultipartRequestBody AdminUploadSpecializationCoverMultipartBody

// AdminMoveSpecializationJSONRequestBody defines body for AdminMoveSpecialization for application/json ContentType.
type AdminMoveSpecializationJSONRequestBody AdminMoveSpecializationJSONBody

// AdminSetSpecializationPublishedJSONRequestBody defines body for AdminSetSpecializationPublished for application/json ContentType.
type AdminSetSpecializationPublishedJSONRequestBody AdminSetSpecializationPublishedJSONBody

// AdminUpdateTaskJSONRequestBody defines body for AdminUpdateTask for application/json ContentType.
type AdminUpdateTaskJSONRequestBody = AdminTaskInput

// AdminCreateUserJSONRequestBody defines body for AdminCreateUser for application/json ContentType.
type AdminCreateUserJSONRequestBody AdminCreateUserJSONBody

// AdminUpdateUserJSONRequestBody defines body for AdminUpdateUser for application/json ContentType.
type AdminUpdateUserJSONRequestBody AdminUpdateUserJSONBody

// AdminSetUserPasswordJSONRequestBody defines body for AdminSetUserPassword for application/json ContentType.
type AdminSetUserPasswordJSONRequestBody AdminSetUserPasswordJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

// SaveLessonNotesJSONRequestBody defines body for SaveLessonNotes for application/json ContentType.
type SaveLessonNotesJSONRequestBody SaveLessonNotesJSONBody

// AnswerQuizQuestionJSONRequestBody defines body for AnswerQuizQuestion for application/json ContentType.
type AnswerQuizQuestionJSONRequestBody = QuizAnswerInput

// SubmitQuizJSONRequestBody defines body for SubmitQuiz for application/json ContentType.
type SubmitQuizJSONRequestBody SubmitQuizJSONBody

// RunPlaygroundJSONRequestBody defines body for RunPlayground for application/json ContentType.
type RunPlaygroundJSONRequestBody = RunRequest

// RunTaskCodeJSONRequestBody defines body for RunTaskCode for application/json ContentType.
//
// Deprecated: this type has been marked as deprecated upstream, but no `x-deprecated-reason` was set
type RunTaskCodeJSONRequestBody = RunRequest
